const V1 = '/api/v1';

export const Endpoints = {
  auth: {
    register:       `${V1}/auth/register`,
    login:          `${V1}/auth/login`,
    refresh:        `${V1}/auth/refresh`,
    logout:         `${V1}/auth/logout`,
    me:             `${V1}/auth/me`,
    changePassword: `${V1}/auth/me/password`,
    oauthGoogle:    `${V1}/auth/oauth/google`,
    forgotPassword: `${V1}/auth/forgot-password`,
    resetPassword:  `${V1}/auth/reset-password`,
    webQrGenerate:  `${V1}/auth/web-qr/generate`,
    webQrScan:      `${V1}/auth/web-qr/scan`,
    webQrStatus:    (token: string) => `${V1}/auth/web-qr/status/${token}`,
  },
  users: {
    me:                 `${V1}/users/me`,
    updateMe:           `${V1}/users/me`,
    deleteMe:           `${V1}/users/me`,
    verificationStatus: `${V1}/users/me/verification`,
    verifyRequest:      `${V1}/users/me/verify-request`,
    privacy:            `${V1}/users/me/privacy`,
    publicProfile: (id: string) => `${V1}/users/${id}/profile`,
    userReels:     (id: string) => `${V1}/users/${id}/reels`,
    follow:        (id: string) => `${V1}/users/${id}/follow`,
    followers:     (id: string) => `${V1}/users/${id}/followers`,
    following:     (id: string) => `${V1}/users/${id}/following`,
    block:         (id: string) => `${V1}/users/${id}/block`,
    blocked:       `${V1}/users/me/blocked`,
    suggestions:   `${V1}/users/suggestions`,
    watchHistory:  `${V1}/users/me/history`,
  },
  content: {
    films:          `${V1}/content/films`,
    filmById:       (id: string) => `${V1}/content/films/${id}`,
    filmAccess:     (id: string) => `${V1}/content/films/${id}/access`,
    filmPurchase:   (id: string) => `${V1}/content/films/${id}/purchase`,
    series:         `${V1}/content/series`,
    serieById:      (id: string) => `${V1}/content/series/${id}`,
    serieAccess:    (id: string) => `${V1}/content/series/${id}/access`,
    seriePurchase:  (id: string) => `${V1}/content/series/${id}/purchase`,
    myAccesses:     `${V1}/content/my-accesses`,
  },
  seasons: {
    bySerie: (contentId: string) => `${V1}/content/series/${contentId}/seasons`,
  },
  episodes: {
    bySeason: (contentId: string, seasonNumber: number) => `${V1}/content/series/${contentId}/seasons/${seasonNumber}/episodes`,
    byId:     (episodeId: string) => `${V1}/episodes/${episodeId}`,
  },
  videos: {
    byContent: (contentId: string) => `${V1}/content/${contentId}/videos`,
    byEpisode: (episodeId: string) => `${V1}/episodes/${episodeId}/videos`,
  },
  concerts: {
    list:      `${V1}/concerts`,
    public:    `${V1}/explore/concerts`,
    byUser:    (userId: string) => `${V1}/users/${userId}/concerts`,
    live:      `${V1}/concerts/live`,
    upcoming:  `${V1}/concerts/upcoming`,
    byId:      (id: string) => `${V1}/concerts/${id}`,
    publicById:(id: string) => `${V1}/explore/concerts/${id}`,
    buyTicket: (concertId: string) => `${V1}/concerts/${concertId}/tickets`,
    myTickets: `${V1}/concerts/tickets/me`,
  },
  streaming: {
    token:     (concertId: string) => `${V1}/stream/${concertId}/token`,
    status:    (concertId: string) => `${V1}/stream/${concertId}/status`,
    start:     (concertId: string) => `${V1}/stream/${concertId}/start`,
    stop:      (concertId: string) => `${V1}/stream/${concertId}/stop`,
    analytics: (concertId: string) => `${V1}/stream/${concertId}/analytics`,
    progress:  (videoId: string) => `${V1}/stream/${videoId}/progress`,
  },
  events: {
    list:      `${V1}/events`,
    public:    `${V1}/explore/events`,
    byUser:    (userId: string) => `${V1}/users/${userId}/events`,
    byId:      (id: string) => `${V1}/events/${id}`,
    publicById:(id: string) => `${V1}/explore/events/${id}`,
    buyTicket: (eventId: string) => `${V1}/events/${eventId}/tickets`,
    myTickets: `${V1}/events/tickets/me`,
  },
  reels: {
    feed:   `${V1}/reels`,
    byId:   (id: string) => `${V1}/reels/${id}`,
    view:   (id: string) => `${V1}/reels/${id}/view`,
    byUser: (userId: string) => `${V1}/reels/user/${userId}`,
    delete: (id: string) => `${V1}/reels/${id}`,
  },
  social: {
    comments:       `${V1}/social/comments`,
    commentById:    (id: string) => `${V1}/social/comments/${id}`,
    commentReplies: (id: string) => `${V1}/social/comments/${id}/replies`,
    toggleReaction: `${V1}/social/reactions`,
    reactionCounts: `${V1}/social/reactions/counts`,
    myReaction:     `${V1}/social/reactions/me`,
    share:          `${V1}/social/shares`,
  },
  posts: {
    feed:   `${V1}/posts/feed`,
    byUser: (userId: string) => `${V1}/users/${userId}/posts`,
    create: `${V1}/posts`,
    byId:   (id: string) => `${V1}/posts/${id}`,
    react:  (id: string) => `${V1}/posts/${id}/react`,
    update: (id: string) => `${V1}/posts/${id}`,
  },
  stories: {
    feed:    `${V1}/stories/feed`,
    me:      `${V1}/stories/me`,
    create:  `${V1}/stories`,
    view:    (id: string) => `${V1}/stories/${id}/view`,
    viewers: (id: string) => `${V1}/stories/${id}/viewers`,
    delete:  (id: string) => `${V1}/stories/${id}`,
  },
  messages: {
    conversations: `${V1}/messages/conversations`,
    conversation:  (userId: string) => `${V1}/messages/conversations/${userId}`,
    markRead:      (userId: string) => `${V1}/messages/conversations/${userId}/read`,
    message:       (messageId: string) => `${V1}/messages/messages/${messageId}`,
  },
  communities: {
    list:     `${V1}/communities`,
    mine:     `${V1}/communities/me`,
    discover: `${V1}/communities/discover/list`,
    create:   `${V1}/communities`,
    byId:     (id: string) => `${V1}/communities/${id}`,
    join:     (id: string) => `${V1}/communities/${id}/join`,
    leave:    (id: string) => `${V1}/communities/${id}/leave`,
    role:     (id: string) => `${V1}/communities/${id}/my-role`,
    // Messages
    messages:      (id: string)                    => `${V1}/communities/${id}/messages`,
    message:       (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}`,
    messageById:   (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}`,
    messageReact:  (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}/react`,
    pinnedMessages:(id: string)                    => `${V1}/communities/${id}/messages/pinned`,
    pinMessage:    (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}/pin`,
    // Members
    members:       (id: string)                    => `${V1}/communities/${id}/members`,
    member:        (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}`,
    memberRole:    (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}/role`,
    memberProfile: (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}/profile`,
    memberCreatorStats: (id: string, userId: string) => `${V1}/communities/${id}/members/${userId}/creator-stats`,
    block:         (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}/block`,
    blocked:       (id: string)                    => `${V1}/communities/${id}/blocked`,
    // Join requests
    joinRequests:        (id: string)                             => `${V1}/communities/${id}/join-requests`,
    approveJoinRequest:  (id: string, reqId: string)             => `${V1}/communities/${id}/join-requests/${reqId}/approve`,
    rejectJoinRequest:   (id: string, reqId: string)             => `${V1}/communities/${id}/join-requests/${reqId}/reject`,
    // Channels
    channels:        (id: string)                                => `${V1}/communities/${id}/channels`,
    channel:         (id: string, chId: string)                  => `${V1}/communities/${id}/channels/${chId}`,
    channelMessages: (id: string, chId: string)                  => `${V1}/communities/${id}/channels/${chId}/messages`,
    channelMessage:  (id: string, chId: string, msgId: string)   => `${V1}/communities/${id}/channels/${chId}/messages/${msgId}`,
    channelMembers:  (id: string, chId: string)                  => `${V1}/communities/${id}/channels/${chId}/members`,
    // Leaderboard
    leaderboard:   (id: string) => `${V1}/communities/${id}/leaderboard`,
    myLeaderboard: (id: string) => `${V1}/communities/${id}/leaderboard/me`,
    // Stats
    stats: (id: string) => `${V1}/communities/${id}/stats`,
    // Events
    events:    (id: string)                          => `${V1}/communities/${id}/events`,
    event:     (id: string, evId: string)            => `${V1}/communities/${id}/events/${evId}`,
    eventRsvp: (id: string, evId: string)            => `${V1}/communities/${id}/events/${evId}/rsvp`,
    // Verification
    verificationRequest: (id: string) => `${V1}/communities/${id}/verification-request`,
  },
  search: {
    query:    `${V1}/search`,
    trending: `${V1}/search/trending`,
    feed:     `${V1}/search/feed`,
  },
  subscriptions: {
    plans:          `${V1}/plans`,
    me:             `${V1}/subscriptions/me`,
    subscribe:      `${V1}/subscriptions`,
    subscribeWallet:(plan: string) => `${V1}/subscriptions/wallet?plan=${plan}`,
    walletCheck:    (plan: string) => `${V1}/subscriptions/wallet-check?plan=${plan}`,
    cancel:         `${V1}/subscriptions/me`,
    history:        `${V1}/subscriptions/history`,
  },
  notifications: {
    list:       `${V1}/notifications`,
    unreadCount:`${V1}/notifications/unread-count`,
    readAll:    `${V1}/notifications/read-all`,
    deleteAll:  `${V1}/notifications`,
    read:       (id: string) => `${V1}/notifications/${id}/read`,
    delete:     (id: string) => `${V1}/notifications/${id}`,
  },
  upload: {
    images: (folder: string) => `${V1}/upload/images?folder=${folder}`,
    video:  (folder: string) => `${V1}/upload/video?folder=${folder}`,
  },
  lives: {
    list:      `${V1}/lives`,
    me:        `${V1}/lives/me`,
    start:     `${V1}/lives/start`,
    byId:      (id: string) => `${V1}/lives/${id}`,
    stop:      (id: string) => `${V1}/lives/${id}/stop`,
    token:     (id: string) => `${V1}/lives/${id}/token`,
    status:    (id: string) => `${V1}/lives/${id}/status`,
    like:      (id: string) => `${V1}/lives/${id}/like`,
    react:     (id: string) => `${V1}/lives/${id}/react`,
    handRaise: (id: string, identity: string) => `${V1}/lives/${id}/hand-raise/${identity}`,
    invite:    (id: string, identity: string) => `${V1}/lives/${id}/invite/${identity}`,
    demote:    (id: string, identity: string) => `${V1}/lives/${id}/demote/${identity}`,
    ban:       (id: string, identity: string) => `${V1}/lives/${id}/ban/${identity}`,
    globalBan: (id: string, identity: string) => `${V1}/lives/${id}/global-ban/${identity}`,
  },
  activity: {
    feed:   `${V1}/activity/feed`,
    delete: (id: string) => `${V1}/activity/feed/${id}`,
  },
  wallet: {
    balance:        `${V1}/wallet/me`,
    transfer:       `${V1}/wallet/transfer`,
    transactions:   `${V1}/wallet/transactions`,
    packages:       `${V1}/wallet/packages`,
    purchase:       `${V1}/wallet/purchase`,
    purchaseCustom: `${V1}/wallet/purchase/custom`,
    withdraw:       `${V1}/wallet/withdraw`,
    creatorProfile: `${V1}/wallet/creator/profile`,
    creatorStats:   `${V1}/wallet/creator/stats`,
    creatorReels:   `${V1}/wallet/creator/reels`,
    creatorGifts:   `${V1}/wallet/creator/gifts`,
    boostsPurchase: `${V1}/wallet/boosts/purchase`,
    gifts:          `${V1}/wallet/gifts`,
    sendGift:       `${V1}/wallet/gifts/send`,
    referralMe:     `${V1}/wallet/referral/me`,
    referralStats:  `${V1}/wallet/referral/stats`,
    referralUsers:  `${V1}/wallet/referral/users`,
    monetizationStatus: `${V1}/wallet/monetization/status`,
    monetizationRequest:`${V1}/wallet/monetization/request`,
  },
  favorites: {
    list:   (type: string) => `${V1}/favorites?type=${type}`,
    remove: (id: string) => `${V1}/favorites/${id}`,
  },
  planning: {
    feed:    `${V1}/planning`,
    entries: `${V1}/planning/entries`,
    entry:   (id: string) => `${V1}/planning/entries/${id}`,
  },
} as const;
