const V1 = '/api/v1';

export const Endpoints = {
  auth: {
    register:       `${V1}/auth/register`,
    login:          `${V1}/auth/login`,
    refresh:        `${V1}/auth/refresh`,
    logout:         `${V1}/auth/logout`,
    me:             `${V1}/auth/me`,
    changePassword: `${V1}/auth/me/password`,
    oauthGoogle:    `${V1}/auth/oauth/google`,
    forgotPassword: `${V1}/auth/forgot-password`,
    resetPassword:  `${V1}/auth/reset-password`,
  },
  users: {
    me:            `${V1}/users/me`,
    updateMe:      `${V1}/users/me`,
    publicProfile: (id: string) => `${V1}/users/${id}/profile`,
    userReels:     (id: string) => `${V1}/users/${id}/reels`,
    follow:        (id: string) => `${V1}/users/${id}/follow`,
    followers:     (id: string) => `${V1}/users/${id}/followers`,
    following:     (id: string) => `${V1}/users/${id}/following`,
    block:         (id: string) => `${V1}/users/${id}/block`,
    blocked:       `${V1}/users/me/blocked`,
    suggestions:   `${V1}/users/suggestions`,
    watchHistory:  `${V1}/users/me/history`,
  },
  content: {
    films:     `${V1}/content/films`,
    filmById:  (id: string) => `${V1}/content/films/${id}`,
    series:    `${V1}/content/series`,
    serieById: (id: string) => `${V1}/content/series/${id}`,
  },
  seasons: {
    bySerie: (contentId: string) => `${V1}/content/series/${contentId}/seasons`,
  },
  episodes: {
    bySeason: (contentId: string, seasonNumber: number) => `${V1}/content/series/${contentId}/seasons/${seasonNumber}/episodes`,
    byId:     (episodeId: string) => `${V1}/episodes/${episodeId}`,
  },
  videos: {
    byContent: (contentId: string) => `${V1}/content/${contentId}/videos`,
    byEpisode: (episodeId: string) => `${V1}/episodes/${episodeId}/videos`,
  },
  concerts: {
    list:      `${V1}/concerts`,
    live:      `${V1}/concerts/live`,
    upcoming:  `${V1}/concerts/upcoming`,
    byId:      (id: string) => `${V1}/concerts/${id}`,
    buyTicket: (concertId: string) => `${V1}/concerts/${concertId}/tickets`,
    myTickets: `${V1}/concerts/tickets/me`,
  },
  streaming: {
    token:    (concertId: string) => `${V1}/stream/${concertId}/token`,
    status:   (concertId: string) => `${V1}/stream/${concertId}/status`,
    progress: (videoId: string) => `${V1}/stream/${videoId}/progress`,
  },
  events: {
    list:      `${V1}/events`,
    byId:      (id: string) => `${V1}/events/${id}`,
    buyTicket: (eventId: string) => `${V1}/events/${eventId}/tickets`,
    myTickets: `${V1}/events/tickets/me`,
  },
  reels: {
    feed:   `${V1}/reels`,
    byId:   (id: string) => `${V1}/reels/${id}`,
    view:   (id: string) => `${V1}/reels/${id}/view`,
    byUser: (userId: string) => `${V1}/reels/user/${userId}`,
    delete: (id: string) => `${V1}/reels/${id}`,
  },
  social: {
    comments:       `${V1}/social/comments`,
    commentById:    (id: string) => `${V1}/social/comments/${id}`,
    commentReplies: (id: string) => `${V1}/social/comments/${id}/replies`,
    toggleReaction: `${V1}/social/reactions`,
    reactionCounts: `${V1}/social/reactions/counts`,
    share:          `${V1}/social/shares`,
  },
  posts: {
    feed:   `${V1}/posts/feed`,
    create: `${V1}/posts`,
    byId:   (id: string) => `${V1}/posts/${id}`,
    react:  (id: string) => `${V1}/posts/${id}/react`,
    update: (id: string) => `${V1}/posts/${id}`,
  },
  stories: {
    feed:   `${V1}/stories/feed`,
    me:     `${V1}/stories/me`,
    create: `${V1}/stories`,
    view:   (id: string) => `${V1}/stories/${id}/view`,
    delete: (id: string) => `${V1}/stories/${id}`,
  },
  messages: {
    conversations: `${V1}/messages/conversations`,
    conversation:  (userId: string) => `${V1}/messages/conversations/${userId}`,
    markRead:      (userId: string) => `${V1}/messages/conversations/${userId}/read`,
    message:       (messageId: string) => `${V1}/messages/messages/${messageId}`,
  },
  communities: {
    list:     `${V1}/communities`,
    mine:     `${V1}/communities/me`,
    discover: `${V1}/communities/discover/list`,
    byId:     (id: string) => `${V1}/communities/${id}`,
    join:     (id: string) => `${V1}/communities/${id}/join`,
    leave:    (id: string) => `${V1}/communities/${id}/leave`,
    messages: (id: string) => `${V1}/communities/${id}/messages`,
  },
  search: {
    query:    `${V1}/search`,
    trending: `${V1}/search/trending`,
    feed:     `${V1}/search/feed`,
  },
  subscriptions: {
    plans:     `${V1}/plans`,
    me:        `${V1}/subscriptions/me`,
    subscribe: `${V1}/subscriptions`,
    cancel:    `${V1}/subscriptions/me`,
  },
  notifications: {
    list:       `${V1}/notifications`,
    unreadCount:`${V1}/notifications/unread-count`,
    readAll:    `${V1}/notifications/read-all`,
    read:       (id: string) => `${V1}/notifications/${id}/read`,
    delete:     (id: string) => `${V1}/notifications/${id}`,
  },
  upload: {
    images: (folder: string) => `${V1}/upload/images?folder=${folder}`,
    video:  (folder: string) => `${V1}/upload/video?folder=${folder}`,
  },
  activity: { feed: `${V1}/activity/feed` },
  planning: {
    feed:    `${V1}/planning`,
    entries: `${V1}/planning/entries`,
    entry:   (id: string) => `${V1}/planning/entries/${id}`,
  },
} as const;
