const V1 = '/api/v1';

export const Endpoints = {
  auth: {
    register:       `${V1}/auth/register`,
    login:          `${V1}/auth/login`,
    refresh:        `${V1}/auth/refresh`,
    logout:         `${V1}/auth/logout`,
    me:             `${V1}/auth/me`,
    changePassword: `${V1}/auth/me/password`,
    oauthGoogle:    `${V1}/auth/oauth/google`,
    forgotPassword:   `${V1}/auth/forgot-password`,
    verifyResetCode:  `${V1}/auth/verify-reset-code`,
    resetPassword:    `${V1}/auth/reset-password`,
    verifyRegistration:     `${V1}/auth/verify-registration`,
    resendVerificationCode: `${V1}/auth/resend-verification-code`,
    webQrGenerate:  `${V1}/auth/web-qr/generate`,
    webQrScan:      `${V1}/auth/web-qr/scan`,
    webQrStatus:    (token: string) => `${V1}/auth/web-qr/status/${token}`,
  },
  users: {
    me:                 `${V1}/users/me`,
    updateMe:           `${V1}/users/me`,
    deleteMe:           `${V1}/users/me`,
    verificationStatus: `${V1}/users/me/verification`,
    verifyRequest:      `${V1}/users/me/verify-request`,
    privacy:            `${V1}/users/me/privacy`,
    publicProfile: (id: string) => `${V1}/users/${id}/profile`,
    userReels:     (id: string) => `${V1}/users/${id}/reels`,
    follow:        (id: string) => `${V1}/users/${id}/follow`,
    followers:     (id: string) => `${V1}/users/${id}/followers`,
    following:     (id: string) => `${V1}/users/${id}/following`,
    block:         (id: string) => `${V1}/users/${id}/block`,
    blocked:       `${V1}/users/me/blocked`,
    suggestions:   `${V1}/users/suggestions`,
    watchHistory:  `${V1}/users/me/history`,
    checkUsername: `${V1}/users/check-username`,
  },
  content: {
    films:          `${V1}/content/films`,
    filmById:       (id: string) => `${V1}/content/films/${id}`,
    filmAccess:     (id: string) => `${V1}/content/films/${id}/access`,
    filmPurchase:   (id: string) => `${V1}/content/films/${id}/purchase`,
    series:         `${V1}/content/series`,
    serieById:      (id: string) => `${V1}/content/series/${id}`,
    serieAccess:    (id: string) => `${V1}/content/series/${id}/access`,
    seriePurchase:  (id: string) => `${V1}/content/series/${id}/purchase`,
    myAccesses:     `${V1}/content/my-accesses`,
  },
  seasons: {
    bySerie: (contentId: string) => `${V1}/content/series/${contentId}/seasons`,
  },
  episodes: {
    bySeason: (contentId: string, seasonNumber: number) => `${V1}/content/series/${contentId}/seasons/${seasonNumber}/episodes`,
    byId:     (episodeId: string) => `${V1}/episodes/${episodeId}`,
  },
  videos: {
    byContent: (contentId: string) => `${V1}/content/${contentId}/videos`,
    byEpisode: (episodeId: string) => `${V1}/episodes/${episodeId}/videos`,
  },
  concerts: {
    list:      `${V1}/concerts`,
    public:    `${V1}/concerts`,
    byUser:    (userId: string) => `${V1}/users/${userId}/concerts`,
    live:      `${V1}/concerts/live`,
    upcoming:  `${V1}/concerts/upcoming`,
    byId:      (id: string) => `${V1}/concerts/${id}`,
    publicById:(id: string) => `${V1}/concerts/${id}`,
    buyTicket: (concertId: string) => `${V1}/concerts/${concertId}/tickets`,
    myTickets: `${V1}/concerts/tickets/me`,
    remind:    (id: string) => `${V1}/concerts/${id}/remind`,
  },
  streaming: {
    token:     (concertId: string) => `${V1}/stream/${concertId}/token`,
    status:    (concertId: string) => `${V1}/stream/${concertId}/status`,
    start:     (concertId: string) => `${V1}/stream/${concertId}/start`,
    stop:      (concertId: string) => `${V1}/stream/${concertId}/stop`,
    analytics: (concertId: string) => `${V1}/stream/${concertId}/analytics`,
    progress:  (videoId: string) => `${V1}/stream/${videoId}/progress`,
  },
  events: {
    list:      `${V1}/events`,
    public:    `${V1}/events`,
    byUser:    (userId: string) => `${V1}/users/${userId}/events`,
    byId:      (id: string) => `${V1}/events/${id}`,
    publicById:(id: string) => `${V1}/events/${id}`,
    buyTicket: (eventId: string) => `${V1}/events/${eventId}/tickets`,
    myTickets: `${V1}/events/tickets/me`,
    remind:    (id: string) => `${V1}/events/${id}/remind`,
  },
  reels: {
    feed:           `${V1}/reels`,
    byId:           (id: string) => `${V1}/reels/${id}`,
    view:           (id: string) => `${V1}/reels/${id}/view`,
    byUser:         (userId: string) => `${V1}/reels/user/${userId}`,
    delete:         (id: string) => `${V1}/reels/${id}`,
    repost:         (id: string) => `${V1}/reels/${id}/repost`,
    toggleComments: (id: string) => `${V1}/social/reel/${id}/comments/toggle`,
  },
  cable: {
    sendInvite: (reelId: string) => `${V1}/cable/reels/${reelId}`,
    myInvites:  `${V1}/cable/invites/me`,
  },
  social: {
    comments:       `${V1}/social/comments`,
    commentById:    (id: string) => `${V1}/social/comments/${id}`,
    commentReplies: (id: string) => `${V1}/social/comments/${id}/replies`,
    toggleReaction: `${V1}/social/reactions`,
    reactionCounts: `${V1}/social/reactions/counts`,
    reactionUsers:  `${V1}/social/reactions/users`,
    myReaction:     `${V1}/social/reactions/me`,
    share:          `${V1}/social/shares`,
    shareCounts:    `${V1}/social/shares/counts`,
  },
  posts: {
    byUser: (userId: string) => `${V1}/users/${userId}/posts`,
    create: `${V1}/posts`,
    byId:   (id: string) => `${V1}/posts/${id}`,
    react:  (id: string) => `${V1}/posts/${id}/react`,
    update: (id: string) => `${V1}/posts/${id}`,
  },
  stories: {
    feed:    `${V1}/stories/feed`,
    me:      `${V1}/stories/me`,
    create:  `${V1}/stories`,
    view:    (id: string) => `${V1}/stories/${id}/view`,
    like:    (id: string) => `${V1}/stories/${id}/like`,
    likers:  (id: string) => `${V1}/stories/${id}/likers`,
    viewers: (id: string) => `${V1}/stories/${id}/viewers`,
    delete:  (id: string) => `${V1}/stories/${id}`,
  },
  messages: {
    conversations:      `${V1}/messages/conversations`,
    conversation:       (userId: string)    => `${V1}/messages/conversations/${userId}`,
    markRead:           (userId: string)    => `${V1}/messages/conversations/${userId}/read`,
    deleteConversation: (userId: string)    => `${V1}/messages/conversations/${userId}`,
    pinnedInConvo:      (userId: string)    => `${V1}/messages/conversations/${userId}/pinned`,
    searchInConvo:      (userId: string)    => `${V1}/messages/conversations/${userId}/search`,
    message:            (messageId: string) => `${V1}/messages/messages/${messageId}`,
    messagePin:         (messageId: string) => `${V1}/messages/messages/${messageId}/pin`,
    messageReact:       (messageId: string) => `${V1}/messages/messages/${messageId}/react`,
    messageForward:     (messageId: string) => `${V1}/messages/messages/${messageId}/forward`,
    messageDeleteForMe: (messageId: string) => `${V1}/messages/messages/${messageId}/for-me`,
    unreadCount:        `${V1}/messages/unread-count`,
    usersSearch:        `${V1}/search`,
    requestStatus:      (userId: string) => `${V1}/messages/conversations/${userId}/request-status`,
    acceptConversation: (userId: string) => `${V1}/messages/conversations/${userId}/accept`,
    blockConversation:  (userId: string) => `${V1}/messages/conversations/${userId}/block`,
  },
  communities: {
    list:     `${V1}/communities`,
    mine:     `${V1}/communities/me`,
    discover: `${V1}/communities/discover/list`,
    create:   `${V1}/communities`,
    byId:     (id: string) => `${V1}/communities/${id}`,
    join:     (id: string) => `${V1}/communities/${id}/join`,
    leave:    (id: string) => `${V1}/communities/${id}/leave`,
    role:     (id: string) => `${V1}/communities/${id}/role`,
    // Messages
    messages:      (id: string)                    => `${V1}/communities/${id}/messages`,
    message:       (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}`,
    messageById:   (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}`,
    messageReact:  (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}/react`,
    pinnedMessages:(id: string)                    => `${V1}/communities/${id}/messages/pinned`,
    pinMessage:    (id: string, msgId: string)     => `${V1}/communities/${id}/messages/${msgId}/pin`,
    // Members
    members:       (id: string)                    => `${V1}/communities/${id}/members`,
    member:        (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}`,
    memberRole:    (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}/role`,
    memberProfile: (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}`,
    memberCreatorStats: (id: string, userId: string) => `${V1}/communities/${id}/members/${userId}/creator-stats`,
    block:         (id: string, userId: string)    => `${V1}/communities/${id}/members/${userId}/block`,
    blocked:       (id: string)                    => `${V1}/communities/${id}/blocked`,
    // Join requests
    joinRequests:        (id: string)                             => `${V1}/communities/${id}/join-requests`,
    approveJoinRequest:  (id: string, reqId: string)             => `${V1}/communities/${id}/join-requests/${reqId}/approve`,
    rejectJoinRequest:   (id: string, reqId: string)             => `${V1}/communities/${id}/join-requests/${reqId}/reject`,
    // Channels
    channels:        (id: string)                                => `${V1}/communities/${id}/channels`,
    channel:         (id: string, chId: string)                  => `${V1}/communities/${id}/channels/${chId}`,
    channelMessages: (id: string, chId: string)                  => `${V1}/communities/${id}/channels/${chId}/messages`,
    channelMessage:  (id: string, chId: string, msgId: string)   => `${V1}/communities/${id}/channels/${chId}/messages/${msgId}`,
    channelMembers:  (id: string, chId: string)                  => `${V1}/communities/${id}/channels/${chId}/members`,
    // Leaderboard
    leaderboard:   (id: string) => `${V1}/communities/${id}/leaderboard`,
    myLeaderboard: (id: string) => `${V1}/communities/${id}/leaderboard/me`,
    // Stats
    stats: (id: string) => `${V1}/communities/${id}/stats`,
    // Events
    events:    (id: string)                          => `${V1}/communities/${id}/events`,
    event:     (id: string, evId: string)            => `${V1}/communities/${id}/events/${evId}`,
    eventRsvp: (id: string, evId: string)            => `${V1}/communities/${id}/events/${evId}/rsvp`,
    // Verification
    verificationRequest: (id: string) => `${V1}/communities/${id}/verification-request`,
    // Treasury / Wallet communautaire
    wallet:              (id: string) => `${V1}/communities/${id}/wallet`,
    walletTransactions:  (id: string) => `${V1}/communities/${id}/wallet/transactions`,
    // Cotisations
    cotisations:         (id: string)                          => `${V1}/communities/${id}/cotisations`,
    cotisationPay:       (id: string, cotId: string)           => `${V1}/communities/${id}/cotisations/${cotId}/pay`,
    // Trésorier
    treasurer:           (id: string)                          => `${V1}/communities/${id}/treasurer`,
    // Élections trésorier
    treasurerElections:  (id: string)                          => `${V1}/communities/${id}/treasurer-elections`,
    activeTreasurerElection: (id: string)                      => `${V1}/communities/${id}/treasurer-elections/active`,
    treasurerElectionVote:   (id: string, electionId: string)  => `${V1}/communities/${id}/treasurer-elections/${electionId}/vote`,
    treasurerElectionClose:  (id: string, electionId: string)  => `${V1}/communities/${id}/treasurer-elections/${electionId}/close`,
    // Retraits
    withdrawalRequests:       (id: string)                          => `${V1}/communities/${id}/withdrawal-requests`,
    withdrawalRequestApprove: (id: string, reqId: string)           => `${V1}/communities/${id}/withdrawal-requests/${reqId}/approve`,
    withdrawalRequestReject:  (id: string, reqId: string)           => `${V1}/communities/${id}/withdrawal-requests/${reqId}/reject`,
  },
  search: {
    query:         `${V1}/search`,
    trending:      `${V1}/search/trending`,
    trendingReels: `${V1}/search/trending/reels`,
    feed:          `${V1}/search/feed`,
  },
  subscriptions: {
    plans:          `${V1}/plans`,
    me:             `${V1}/subscriptions/me`,
    subscribe:      `${V1}/subscriptions`,
    subscribeWallet:(plan: string) => `${V1}/subscriptions/wallet?plan=${plan}`,
    walletCheck:    (plan: string) => `${V1}/subscriptions/wallet-check?plan=${plan}`,
    cancel:         `${V1}/subscriptions/me`,
    history:        `${V1}/subscriptions/history`,
  },
  notifications: {
    list:       `${V1}/notifications`,
    unreadCount:`${V1}/notifications/unread-count`,
    readAll:    `${V1}/notifications/read-all`,
    deleteAll:  `${V1}/notifications`,
    read:       (id: string) => `${V1}/notifications/${id}/read`,
    delete:     (id: string) => `${V1}/notifications/${id}`,
    byRef:      (refId: string) => `${V1}/notifications?ref_id=${refId}&limit=5`,
  },
  upload: {
    images:         (folder: string) => `${V1}/upload/images?folder=${folder}`,
    video:          (folder: string) => `${V1}/upload/video?folder=${folder}`,
    videoJobStatus: (jobId: string)  => `${V1}/upload/video/status/${jobId}`,
  },
  ads: {
    create:     `${V1}/ads`,
    mine:       `${V1}/ads/mine`,
    byId:       (id: string) => `${V1}/ads/${id}`,
    update:     (id: string) => `${V1}/ads/${id}`,
    delete:     (id: string) => `${V1}/ads/${id}`,
    feedNext:   (placement: string) => `${V1}/ads/feed/next?placement=${placement}`,
    impression: (id: string) => `${V1}/ads/${id}/impression`,
    click:      (id: string) => `${V1}/ads/${id}/click`,
  },
  lives: {
    list:      `${V1}/lives`,
    me:        `${V1}/lives/me`,
    start:     `${V1}/lives/start`,
    byId:      (id: string) => `${V1}/lives/${id}`,
    stop:      (id: string) => `${V1}/lives/${id}/stop`,
    token:     (id: string) => `${V1}/lives/${id}/token`,
    status:    (id: string) => `${V1}/lives/${id}/status`,
    like:      (id: string) => `${V1}/lives/${id}/like`,
    react:     (id: string) => `${V1}/lives/${id}/react`,
    handRaise:   (id: string, identity: string) => `${V1}/lives/${id}/hand-raise/${identity}`,
    dismissHand: (id: string, identity: string) => `${V1}/lives/${id}/dismiss-hand/${identity}`,
    invite:    (id: string, identity: string) => `${V1}/lives/${id}/invite/${identity}`,
    demote:    (id: string, identity: string) => `${V1}/lives/${id}/demote/${identity}`,
    ban:         (id: string, identity: string) => `${V1}/lives/${id}/ban/${identity}`,
    globalBan:   (id: string, identity: string) => `${V1}/lives/${id}/global-ban/${identity}`,
    blockUser:   (userId: string)               => `${V1}/lives/block/${userId}`,
    listBlocks:  `${V1}/lives/blocks`,
    listBans:    `${V1}/lives/bans`,
    removeBan:   (userId: string)               => `${V1}/lives/bans/${userId}`,
    monetization:      (id: string) => `${V1}/lives/${id}/monetization`,
    stageMonetization: (id: string) => `${V1}/lives/${id}/stage-monetization`,
    checkAccess:       (id: string) => `${V1}/lives/${id}/access`,
    accessGoGold:       (id: string) => `${V1}/lives/${id}/access/gogold`,
    accessGift:        (id: string) => `${V1}/lives/${id}/access/gift`,
  },
  battles: {
    byId:          (id: string) => `${V1}/battles/${id}`,
    eligible:      (liveId: string, page = 1, limit = 20) => `${V1}/battles/eligible/${liveId}?page=${page}&limit=${limit}`,
    activeForLive: (liveId: string) => `${V1}/battles/active-for-live/${liveId}`,
    active:        (page = 1, limit = 20) => `${V1}/battles/active?page=${page}&limit=${limit}`,
    invite:        `${V1}/battles/invite`,
    respond:       (id: string) => `${V1}/battles/${id}/respond`,
    cancel:        (id: string) => `${V1}/battles/${id}/cancel`,
    token:         (id: string) => `${V1}/battles/${id}/token`,
    react:         (id: string) => `${V1}/battles/${id}/react`,
    end:           (id: string) => `${V1}/battles/${id}/end`,
    ranking:       (id: string) => `${V1}/battles/${id}/ranking`,
    createGoal:    (id: string) => `${V1}/battles/${id}/goals`,
    activeGoal:    (id: string) => `${V1}/battles/${id}/goals/active`,
  },
  tournaments: {
    open:               `${V1}/tournaments/open`,
    active:             (page = 1, limit = 20) => `${V1}/tournaments/active?page=${page}&limit=${limit}`,
    create:             `${V1}/tournaments`,
    update:             (id: string) => `${V1}/tournaments/${id}`,
    delete:             (id: string) => `${V1}/tournaments/${id}`,
    join:               (id: string) => `${V1}/tournaments/${id}/join`,
    leave:              (id: string) => `${V1}/tournaments/${id}/join`,
    pending:            (id: string) => `${V1}/tournaments/${id}/pending`,
    approveParticipant: (id: string, userId: string) => `${V1}/tournaments/${id}/participants/${userId}/approve`,
    rejectParticipant:  (id: string, userId: string) => `${V1}/tournaments/${id}/participants/${userId}/reject`,
    generateBracket:    (id: string) => `${V1}/tournaments/${id}/generate-bracket`,
    bracket:            (id: string) => `${V1}/tournaments/${id}/bracket`,
    standings:          (id: string) => `${V1}/tournaments/${id}/standings`,
    finance:            (id: string) => `${V1}/tournaments/${id}/finance`,
    reward:             (id: string) => `${V1}/tournaments/${id}/reward`,
    cancel:             (id: string) => `${V1}/tournaments/${id}/cancel`,
    matchReady:         (matchId: string) => `${V1}/tournaments/matches/${matchId}/ready`,
    matchForfeit:       (matchId: string) => `${V1}/tournaments/matches/${matchId}/forfeit`,
  },
  activity: {
    feed:   `${V1}/activity/feed`,
    delete: (id: string) => `${V1}/activity/feed/${id}`,
  },
  wallet: {
    balance:        `${V1}/wallet/me`,
    transfer:       `${V1}/wallet/transfer`,
    transactions:   `${V1}/wallet/transactions`,
    packages:       `${V1}/wallet/packages`,
    purchase:       `${V1}/wallet/purchase`,
    purchaseCustom: `${V1}/wallet/purchase/custom`,
    withdraw:       `${V1}/wallet/withdraw`,
    creatorProfile: `${V1}/wallet/creator/profile`,
    creatorStats:   `${V1}/wallet/creator/stats`,
    creatorReels:   `${V1}/wallet/creator/top-reels`,
    creatorGifts:   `${V1}/wallet/creator/recent-gifts`,
    revenueSummary:      `${V1}/wallet/creator/revenue/summary`,
    revenueTimeseries:   `${V1}/wallet/creator/revenue/timeseries`,
    revenueBreakdown:    `${V1}/wallet/creator/revenue/breakdown`,
    revenueByContent:    `${V1}/wallet/creator/revenue/by-content`,
    revenueTransactions: `${V1}/wallet/creator/revenue/transactions`,
    boostsPurchase: `${V1}/wallet/boosts/purchase`,
    gifts:          `${V1}/wallet/gifts`,
    sendGift:       `${V1}/wallet/gifts/send`,
    referralMe:     `${V1}/wallet/referral/me`,
    referralStats:  `${V1}/wallet/referral/stats`,
    referralUsers:  `${V1}/wallet/referral/users`,
    cinetpayInit:   `${V1}/wallet/purchase/cinetpay/init`,
    cinetpayStatus: (merchantTxId: string) => `${V1}/wallet/purchase/cinetpay/${merchantTxId}/status`,
    stripeConfig:   `${V1}/wallet/stripe/config`,
    stripeInit:     `${V1}/wallet/purchase/stripe/init`,
  },
  monetization: {
    status:  `${V1}/monetization/status`,
    request: `${V1}/monetization/request`,
  },
  favorites: {
    list:   (type: string) => `${V1}/favorites?type=${type}`,
    add:    `${V1}/favorites`,
    remove: (id: string) => `${V1}/favorites/${id}`,
  },
  reports: {
    create: `${V1}/reports`,
    me:     `${V1}/reports/me`,
  },
  planning: {
    feed:    `${V1}/planning`,
    entries: `${V1}/planning/entries`,
    entry:   (id: string) => `${V1}/planning/entries/${id}`,
  },
  utils: {
    linkPreview: (url: string) => `${V1}/utils/link-preview?url=${encodeURIComponent(url)}`,
  },
  social_ext: {
    friendsWhoLiked: (entityType: string, entityId: string) => {
      const key = entityType === 'post' ? 'post_id'
                : entityType === 'event' ? 'event_id'
                : entityType === 'concert' ? 'concert_id'
                : entityType === 'reel' ? 'reel_id'
                : 'post_id';
      return `${V1}/social/reactions/friends?${key}=${entityId}`;
    },
  },

  app: {
    version: `${V1}/app/version`,
  },

  sounds: {
    list:    `${V1}/sounds`,
    popular: `${V1}/sounds/popular`,
    my:      `${V1}/sounds/my`,
    create:  `${V1}/sounds`,
    upload:  `${V1}/sounds/upload`,
    get:     (id: string) => `${V1}/sounds/${id}`,
    use:     (id: string) => `${V1}/sounds/${id}/use`,
  },

  analytics: {
    overview:      `${V1}/analytics/overview`,
    timeseries:    `${V1}/analytics/timeseries`,
    geo:           `${V1}/analytics/geo`,
    reach:         `${V1}/analytics/reach`,
    content:       `${V1}/analytics/content`,
    contentDetail: (contentType: string, contentId: string) => `${V1}/analytics/content/${contentType}/${contentId}`,
  },
} as const;
